# Generated by Django 5.2.1 on 2025-09-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_name_en_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='categoryThrough',
        ),
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='postThrough',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categoryType_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categoryType_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory_ru',
        ),
        migrations.DeleteModel(
            name='PostCategory_en',
        ),
        migrations.DeleteModel(
            name='PostCategory_ru',
        ),
    ]
